[font]
normal = { family = "MesloLGS NF", style = "Regular" }
bold = { family = "MesloLGS NF", style = "Bold" }
italic = { family = "MesloLGS NF", style = "Italic" }
bold_italic = { family = "MesloLGS NF", style = "Bold Italic" }
size = 13.0
offset = { x  = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[selection]
save_to_clipboard = true

[window]
opacity = 0.85

[colors]
transparent_background_colors = true

[colors.primary]
background = "#0A0A00"

