[font]
normal = { family = "JetBrains Mono SemiBold" }
bold = { family = "JetBrains Mono ExtraBold" }
italic = { family = "JetBrains Mono SemiBold", style = "Italic" }
bold_italic = { family = "JetBrains Mono ExtraBold", style = "Italic" }
size = 13.0
offset = { x  = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }

[selection]
save_to_clipboard = true

[window]
opacity = 0.85

[colors]
transparent_background_colors = true

[colors.primary]
background = "#000000"

